apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datahub-encryption-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infra-default
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: datahub
  target:
    template:
      engineVersion: v2
      metadata:
        labels:
          name: datahub-encryption-secrets
      data:
        encryption_key_secret: |
          {{`{{ .encryption_key_secret }}`}}
