apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datahub-okta-oidc-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infra-default
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: datahub
  target:
    template:
      engineVersion: v2
      metadata:
        labels:
          name: datahub-okta-oidc-secret
      data:
        secret: |
          {{`{{ .datahub_okta_oidc_secret_secret }}`}}
