apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datahub-auth-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infra-default
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: datahub
      rewrite:
        - regexp:
            source: "system_client_secret"
            target: "system_client_secret"
        - regexp:
            source: "token_service_salt"
            target: "token_service_salt"
        - regexp:
            source: "token_service_signing_key"
            target: "token_service_signing_key"
  target:
    template:
      engineVersion: v2
      metadata:
        labels:
          name: datahub-auth-secrets
