apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datahub-gms-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infra-default
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: datahub
        decodingStrategy: Base64
  target:
    template:
      engineVersion: v2
      metadata:
        labels:
          name: datahub-gms-secret
      data:
        datahub.gms.secret: |
          {{`{{ .datahub_gms_secret }}`}}
