apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datahub-auth-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infra-default
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: datahub
  target:
    template:
      engineVersion: v2
      metadata:
        labels:
          name: datahub-auth-secrets
      data:
        system_client_secret: |
          {{`{{ .system_client_secret | toString }}`}}
        token_service_salt: |
          {{`{{ .token_service_salt }}`}}
        token_service_signing_key: |
          {{`{{ .token_service_signing_key }}`}}
