apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infra-default
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: datahub
      rewrite:
        - regexp:
            source: "mysql_root_password"
            target: "mysql-root-password"
  target:
    template:
      engineVersion: v2
      metadata:
        labels:
          name: mysql-secrets
