apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: neo4j-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infra-default
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: datahub
      rewrite:
        - regexp:
            source: "neo4j_password"
            target: "neo4j-password"
  target:
    template:
      engineVersion: v2
      metadata:
        labels:
          name: neo4j-secrets
      data:
        neo4j-password: |
          {{`{{ .neo4j_password }}`}}
