apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3-access-key
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infra-default
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: datahub
      rewrite:
        - regexp:
            source: "backup_user_access_key"
            target: "s3.client.default.access_key"
  target:
    template:
      engineVersion: v2
      metadata:
        labels:
          name: s3-access-key
