apiVersion: batch/v1
kind: CronJob
metadata:
  name: dh-mysql-backup
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          nodeSelector:
            eks.amazonaws.com/nodegroup: {{ .Values.myNodeGroup }}
          containers:
            - name: dh-mysql-backup
              # Refer to custom_images/datahub-mysqldump/Dockerfile
              image: 314716043882.dkr.ecr.ap-northeast-2.amazonaws.com/dataplatform/rivendell:datahub-mysqldump
              resources:
                requests:
                  memory: 2Gi
              env:
                - name: MYSQL_PWD
                  valueFrom:
                    secretKeyRef:
                      name: mysql-secrets
                      key: mysql-root-password
                - name: SVC_MYSQL
                  value: prerequisites-mysql
                - name: DB_NAME
                  value: datahub
                - name: TABLE_NAME
                  value: metadata_aspect_v2
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: s3-access-key
                      key: s3.client.default.access_key
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: s3-secret-key
                      key: s3.client.default.secret_key
                - name: S3_BUCKET
                  value: {{ .Values.backup_s3_bucket }}
              args:
                - /bin/sh
                - -c
                - NOW=$(date "+%Y-%m-%dT%H-%M-%S");
                  mysqldump -h ${SVC_MYSQL} ${DB_NAME} ${TABLE_NAME} > dump_{{ .Release.Namespace }}_${NOW}.sql;
                  aws s3 cp dump_{{ .Release.Namespace }}_${NOW}.sql ${S3_BUCKET}/;
