# used as global variables
myNodeGroup: &default-node-group "dataplatform-apne2-airflow-local-stg-datahub_nodegroup"


datahub-gms:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: eks.amazonaws.com/nodegroup
                operator: In
                values:
                  - *default-node-group

datahub-frontend:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: eks.amazonaws.com/nodegroup
                operator: In
                values:
                  - *default-node-group
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: 'arn:aws:acm:ap-northeast-2:232797014574:certificate/a74d9ef9-f4f2-4ebf-b6ee-04d42929b1ac'
  extraEnvs:
    - name: AUTH_OIDC_ENABLED
      value: "true"
    - name: AUTH_OIDC_CLIENT_ID
      value: '0oa6zopvrenQfunXG4x7'
    - name: AUTH_OIDC_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: datahub-okta-oidc-secret
          key: secret
    - name: AUTH_OIDC_DISCOVERY_URI
      value: 'https://sendbird.okta.com/.well-known/openid-configuration'
    - name: AUTH_OIDC_BASE_URL
      value: 'https://datahub.dp-stg.sendbirdtest.com'
    - name: AUTH_OIDC_SCOPE
      value: 'openid profile email groups'
