# used as global variables
backup_s3_bucket: "s3://dataplatform-apne2-datahub-backup-data-stg/mysql"

datahub-frontend:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: 'arn:aws:acm:ap-northeast-2:232797014574:certificate/a74d9ef9-f4f2-4ebf-b6ee-04d42929b1ac'
  extraEnvs:
    - name: AUTH_OIDC_ENABLED
      value: "true"
    - name: AUTH_OIDC_EXTRACT_GROUPS_ENABLED
      value: "true"
    - name: AUTH_OIDC_CLIENT_ID
      value: '0oa6zopvrenQfunXG4x7'
    - name: AUTH_OIDC_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: datahub-okta-oidc-secret
          key: secret
    - name: AUTH_OIDC_DISCOVERY_URI
      value: 'https://sendbird.okta.com/.well-known/openid-configuration'
    - name: AUTH_OIDC_BASE_URL
      value: 'https://datahub.dp-stg.sendbirdtest.com'
    - name: AUTH_OIDC_SCOPE
      value: 'openid profile email groups'

acryl-datahub-actions:
  image:
    repository: 314716043882.dkr.ecr.ap-northeast-2.amazonaws.com/dataplatform/rivendell
    tag: "custom-datahub-actions-v0.0.11-stg"
  extraEnvs:
    - name: PYTHONPATH
      value: /etc/datahub
    - name: GMS_ENDPOINT
      value: 'http://datahub-gms.dp-stg.sendbirdtest.com:8080'
    - name: ENV
      value: stg
